
import React from 'react';
import type { ImageDisplayProps } from '../types';
import { ImageIcon } from './icons/ImageIcon';
import { SpinnerIcon } from './icons/SpinnerIcon';

const getAspectRatioClass = (ratio: string): string => {
  switch (ratio) {
    case '1:1': return 'aspect-square';
    case '4:3': return 'aspect-[4/3]';
    case '3:4': return 'aspect-[3/4]';
    case '16:9': return 'aspect-video';
    case '9:16': return 'aspect-[9/16]';
    default: return 'aspect-square';
  }
};

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, isLoading, error, prompt, aspectRatio }) => {
  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="flex flex-col items-center justify-center h-full text-cyan-300">
          <SpinnerIcon className="w-16 h-16" />
          <p className="mt-4 text-lg font-orbitron tracking-widest">COMPILING PHOTONS...</p>
        </div>
      );
    }

    if (error) {
      return (
        <div className="flex flex-col items-center justify-center h-full text-red-400 p-8 text-center">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-12 w-12 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <p className="text-xl font-semibold font-orbitron">TRANSMISSION ERROR</p>
          <p className="text-red-500 mt-2 font-exo">{error}</p>
        </div>
      );
    }

    if (imageUrl) {
      return (
        <img
          src={imageUrl}
          alt={prompt || 'Generated by AI'}
          className="w-full h-full object-contain rounded-md transition-opacity duration-500 opacity-0 animate-fade-in"
          onLoad={(e) => e.currentTarget.style.opacity = '1'}
        />
      );
    }

    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-600">
        <ImageIcon className="w-24 h-24" />
        <p className="mt-4 text-xl text-center font-orbitron text-slate-500">AWAITING NEURAL INPUT</p>
        <p className="text-slate-600 font-exo">Initiate generation sequence.</p>
      </div>
    );
  };

  return (
    <div className={`${getAspectRatioClass(aspectRatio)} w-full bg-slate-900/50 rounded-lg shadow-lg border border-cyan-400/30 flex items-center justify-center p-4 overflow-hidden backdrop-blur-sm`}>
      <style>{`
        @keyframes fade-in {
          from { opacity: 0; transform: scale(0.98); }
          to { opacity: 1; transform: scale(1); }
        }
        .animate-fade-in {
          animation: fade-in 0.5s ease-out forwards;
        }
      `}</style>
      {renderContent()}
    </div>
  );
};
